# -*- makefile-bsdmake -*-

bmake_topdir = ..

SUBDIR =	api
SUBDIR +=	parsing

.include <bsd.subdir.mk>

# note to do a local rebuild you can also do:  MAKEOBJDIRPREFIX=../build make
#
# Local Variables:
# eval: (make-local-variable 'compile-command)
# compile-command: (concat "cd .. && mkdir -p build && MAKEOBJDIRPREFIX=$(pwd -P)/build " (default-value 'compile-command))
# End:
