# -*- makefile-bsdmake -*-

#	Common/shared setup for this project.
#
# This file contains general but project-specific settings that might be needed
# in sub-directories.  It is included, if it exists, by Makefile.inc.
#
# n.b.:  if this project is moved into a BSD source tree then this file should
# be renamed to Makefile.inc there.

# The common name of the package.
#
# For a library package this is either the library's simple name, else it is the
# library's simple name prefixed by "lib".  Ideally it is the same as the base
# of PKGNAME in the pkgsrc module.
#
PACKAGE_NAME =	yajl

# this project is all pure standard C
#
CSTD = c99
CWARNFLAGS += -pedantic

# The API says: "#include <yajl/yajl.h>"
#
INCSUBDIR =	/yajl

# Attempts will/should be made to conform to Semantic Versioning rules:
#
#	https://semver.org/
#
LIB_MAJOR =	2
LIB_MINOR =	2
LIB_MICRO =	91

# The full version ID for the library
#
LIB_VERSION =	${LIB_MAJOR}.${LIB_MINOR}.${LIB_MICRO}
