name: C CI

# xxx could be written as:  "on: [push, pull_request]"
on:
  push:
    branches: [ bsdmake ]
  pull_request:
    branches: [ bsdmake ]

jobs:
  regressionTest:
    name: "${{ matrix.os }} ${{ matrix.make }} CC=${{ matrix.cc }} ${{ matrix.sanitizer }}=yes CXREF=${{ matrix.docs }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # https://docs.github.com/en/actions/reference/runners/github-hosted-runners#standard-github-hosted-runners-for-public-repositories
        #
        # latest runners:
        #
        #    ubuntu-22.04, ubuntu-24.04
        #    ubuntu-22.04-arm, ubuntu-24.04-arm
        #    macos-15-intel, macos-26-intel
        #    macos-14, macos-15, macos-26
        #
        # N.B. ToDo:  NetBSD et al VMs:  https://github.com/vmactions
        #
        os: [
          ubuntu-latest,
          macos-latest,
          #ubuntu-24.04, ubuntu-22.04,
          #ubuntu-24.04-arm, ubuntu-22.04-arm,
          #macos-26-intel, macos-15-intel,
          #macos-26, macos-15, macos-14
        ]
        cc: [ gcc, clang ]
        make: [ bmake, make ]
        sanitizer: [ NO_SANI, USE_ASAN, USE_UBSAN, USE_LEAKSAN ]
        docs: [ cxref, true ]
        # XXX this isn't the ideal way to handle a binary option?
        parallel: [ '-j 3', '' ]
        exclude:
        #
        # N.B.:  here we _EXCLUDE_ the matrix options we don't want!
        #
        # MacOS 15.x Intel
        - os: macos-15-intel
          # it's clang anyway
          cc: gcc
        - os: macos-15-intel
          # make is gmake
          make: make
        - os: macos-15-intel
          docs: cxref
        - os: macos-15-intel
          parallel: ''
        #
        # MacOS 26 Intel
        - os: macos-26-intel
          # it's clang anyway
          cc: gcc
        - os: macos-26-intel
          # make is gmake
          make: make
        - os: macos-26-intel
          docs: cxref
        - os: macos-26-intel
          parallel: ''
        #
        # MacOS 14.x Arm
        - os: macos-14
          # it's clang anyway
          cc: gcc
        - os: macos-14
          # make is gmake
          make: make
        - os: macos-14
          docs: cxref
        - os: macos-14
          parallel: ''
        #
        # MacOS 15.x Arm
        - os: macos-15
          # it's clang anyway
          cc: gcc
        - os: macos-15
          # make is gmake
          make: make
        - os: macos-15
          docs: cxref
        - os: macos-15
          parallel: ''
        #
        # MacOS 26.x Arm
        - os: macos-26
          # it's clang anyway
          cc: gcc
        - os: macos-26
          # make is gmake
          make: make
        - os: macos-26
          docs: cxref
        - os: macos-26
          parallel: ''
        #
        # MacOS-latest Arm
        - os: macos-latest
          # it's clang anyway
          cc: gcc
        - os: macos-latest
          # make is gmake
          make: make
        - os: macos-latest
          docs: cxref
        - os: macos-latest
          parallel: ''
        #
        # Ubuntu 24.04
        - os: ubuntu-24.04
          # it's gmake
          make: make
        - os: ubuntu-24.04
          docs: true
        - os: ubuntu-24.04
          parallel: ''
        #
        # Ubuntu 22.04
        - os: ubuntu-22.04
          # it's gmake
          make: make
        - os: ubuntu-22.04
          docs: true
        - os: ubuntu-22.04
          parallel: ''
        #
        # Ubuntu 24.04-arm
        - os: ubuntu-24.04-arm
          # it's gmake
          make: make
        - os: ubuntu-24.04-arm
          docs: true
        - os: ubuntu-24.04-arm
          parallel: ''
        #
        # Ubuntu 22.04-arm
        - os: ubuntu-22.04-arm
          # it's gmake
          make: make
        - os: ubuntu-22.04-arm
          docs: true
        - os: ubuntu-22.04-arm
          parallel: ''
        #
        # Ubuntu 20.04
        - os: ubuntu-20.04
          # it's gmake
          make: make
        - os: ubuntu-20.04
          # cxref trips an error in a system header
          # /usr/include/x86_64-linux-gnu/bits/mathcalls-helper-functions.h:21: cxref: syntax error, unexpected IDENTIFIER, expecting ')'
          docs: cxref
        - os: ubuntu-20.04
          # BMake 20181221 seems to run SUBDIR in parallel, but doesn't
          # support .WAIT in the list!
          parallel: '-j 3'
        - os: ubuntu-20.04
          # gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0 with
          # -fsanitize=leak is broken (at least for example/parse_config):
          # https://bugs.launchpad.net/ubuntu/+source/gcc-defaults/+bug/2038386
          sanitizer: USE_LEAKSAN
        #
        # Ubuntu latest
        - os: ubuntu-latest
          # it's gmake
          make: make
        - os: ubuntu-latest
          docs: true
        - os: ubuntu-latest
          parallel: ''
        #
        # NetBSD
        - os: netbsd-latest
          # xxx or we could also install bmake
          make: bmake
        - os: netbsd-latest
          cc: clang
        - os: netbsd-latest
          docs: true
        - os: netbsd-latest
          parallel: ''
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Find out who I am
      run: |
        uname -a
        w
    - name: Check macOS software versions
      if: ${{ startsWith(matrix.os, 'macos') }}
      run: |
        sw_vers
    - name: Install Ubuntu dependencies
      if: ${{ startsWith(matrix.os, 'ubuntu') }}
      run: |
        sudo apt-get update
        sudo apt-get install bmake cxref
    - name: Install MacOS dependencies
      if: ${{ startsWith(matrix.os, 'macos') }}
      # n.b.:  cxref is in macports.... which apparently can be installed like this:
      # wget https://github.com/macports/macports-base/releases/download/v2.9.1/MacPorts-2.9.1-14-Sonoma.pkg
      # sudo installer -pkg ./MacPorts-2.9.1-14-Sonoma.pkg -target /
      run: |
        ls -l /Developer/usr/bin/bsdmake || true
        brew update
        brew install bmake
    - name: Install NetBSD dependencies
      if: ${{ startsWith(matrix.os, 'netbsd') }}
      run: |
        # pkg_add pkgin
        pkgin install cxref
        # pkgin install bmake
    - name: Review toolchain versions
      run: |
        ${{ matrix.make }} -V MAKE_VERSION
        ${{ matrix.cc }} --version
        ${{ matrix.cc }} -v
        $(${{ matrix.make }} -V LD) -v
    - name: Create the build directory and do make obj
      # n.b.:  using MAKEOBJDIRPREFIX pretty much requires a separate "make obj"
      run: |
        rm -rf build && mkdir build
        MAKEOBJDIRPREFIX=$(pwd -P)/build ${{ matrix.make }} ${{ matrix.parallel }} CC=${{ matrix.cc }} ${{ matrix.sanitizer }}=yes CXREF=${{ matrix.docs }} obj || true
    - name: Reveal the make and shell environments
      run: |
        MAKEOBJDIRPREFIX=$(pwd -P)/build ${{ matrix.make }} ${{ matrix.parallel }} CC=${{ matrix.cc }} ${{ matrix.sanitizer }}=yes CXREF=${{ matrix.docs }} showenv
        echo ========================================
        echo Actual Environment:
        env | sort
    - name: Run the build
      run: |
        MAKEOBJDIRPREFIX=$(pwd -P)/build ${{ matrix.make }} ${{ matrix.parallel }} CC=${{ matrix.cc }} ${{ matrix.sanitizer }}=yes CXREF=${{ matrix.docs }} all
    - name: Make the distribution (without parallel)
      # XXX BMake does not seem to handle parallel installs well yet....
      if: ${{ startsWith(matrix.make, 'bmake') }}
      run: |
        MAKEOBJDIRPREFIX=$(pwd -P)/build ${{ matrix.make }} CC=${{ matrix.cc }} ${{ matrix.sanitizer }}=yes CXREF=${{ matrix.docs }} DESTDIR=$(pwd -P)/dist install
    - name: Make the distribution (with parallel)
      if: ${{ ! startsWith(matrix.make, 'bmake') }}
      run: |
        MAKEOBJDIRPREFIX=$(pwd -P)/build ${{ matrix.make }} ${{ matrix.parallel }} CC=${{ matrix.cc }} ${{ matrix.sanitizer }}=yes CXREF=${{ matrix.docs }} DESTDIR=$(pwd -P)/dist install
    - name: Run regression tests
      run: |
        MAKEOBJDIRPREFIX=$(pwd -P)/build ${{ matrix.make }} -d -Ccdfpvm ${{ matrix.parallel }} CC=${{ matrix.cc }} ${{ matrix.sanitizer }}=yes CXREF=${{ matrix.docs }} regress
